version: '3.9'

services:
  menufy:
    container_name: menufy
    build: .
    image: menufy
    ports:
      - "8000:8000"
    depends_on:
      - go_db

  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 3035
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}